// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aptwrtpbdylldrfycqej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdHdydHBiZHlsbGRyZnljcWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1Njk4NTksImV4cCI6MjA4MzE0NTg1OX0.IjClzT_j-c_9Rk4iWH_3puWy8zisNi5NbFR50e2C1TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});